name: Cypress Tests with Dependency and Artifact Caching

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Eğer client klasörü yoksa bu satırı kaldırın
          working-directory: client
          runTests: false
          # build komutunu kaldırdık çünkü henüz bağımlılıklar yüklenmedi
          # build: npm run build

      # Bağımlılıkları yükleyelim
      - name: Install dependencies
        run: npm ci
        # Eğer client klasörü varsa:
        # working-directory: client

      # Şimdi build işlemini gerçekleştirelim
      - name: Build
        run: npm run build
        # Eğer client klasörü varsa:
        # working-directory: client

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build  # Eğer client klasöründeyse: client/build

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build  # Eğer client klasöründeyse: client/build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          # Eğer client klasörü varsa:
          # working-directory: client